export const data = [
  {
    id: 1,
    image: "/images/image-brownie-mobile.jpg",
    name: "Waffle with Berries",
    category: "Waffle",
    price: 6.5,
  },
  {
    id: 2,
    image: "/images/image-creme-brulee-mobile.jpg",
    name: "Vanilla Bean Crème Brûlée",
    category: "Crème Brûlée",
    price: 7.0,
  },
  {
    id: 3,
    image: "/images/image-macaron-mobile.jpg",
    name: "Macaron Mix of Five",
    category: "Macaron",
    price: 8.0,
  },
  {
    id: 4,
    image: "/images/image-tiramisu-mobile.jpg",
    name: "Classic Tiramisu",
    category: "Tiramisu",
    price: 5.5,
  },
  {
    id: 5,
    image: "/images/image-baklava-mobile.jpg",
    name: "Pistachio Baklava",
    category: "Baklava",
    price: 4.0,
  },
  {
    id: 6,
    image: "/images/image-meringue-mobile.jpg",
    name: "Lemon Meringue Pie",
    category: "Pie",
    price: 5.0,
  },
  {
     id: 7,
     image: "/images/image-cake-mobile.jpg",
     name: "Red Velvet Cake",
     category: "cake",
     price: 4.5,
   },
   {
      id: 8,
      image: "/images/image-brownie-thumbnail.jpg",
      name: "Salted Caramel Brownie",
      category: "Brownie",
      price: 4.5,
   },
   {
    id: 9,
    image: "/images/image-panna-cotta-mobile.jpg",
    name: "Vanilla Panna Cotta",
    category: "Panna Cotta",
    price: 6.5,
  },
];
